### ISSUE TITLE
few problems with auth

### ISSUE THREAD

**Issue by GigaGiorgadze** [ninadarbaidze/movie-quotes-front-ninadarbaidze#29]
![image](https://user-images.githubusercontent.com/75663118/189309648-17c739a3-60d8-4d9b-8489-2bfb580e2d2c.png)
so look this is old user, when I press login i get redirected  to newsfeed page and I get this error: 
![image](https://user-images.githubusercontent.com/75663118/189309928-73b6939b-5ec8-4894-b7db-e2a79074b65f.png)
u should check on server side if user is correct or when u fetch data, and if its wrong u should log me out and also as logged in user i should not be allowed on login page

**Comment by ninadarbaidze** [comment]
Yes I've implemented that functionality, If the user is logged in, they cannot see the login page and they're automatically redirected to feed.

What happened is that I deleted all the users a few days ago, because I changed the user model and the old user data wasn't compatible with the new one. 

I also have logic, it checks if the token is expired and automatically logs out. As it seems your token was still valid and the user deleted. The one thing I can do is to check if user exists along with token validity

**Comment by GigaGiorgadze** [comment]
yea do that, way JWT works is just checks for validity to actually log out and destroy JWT u need to add it to some sort of blacklist but that is going bit too far for this, also just check user and it should be fine

**Comment by GigaGiorgadze** [comment]
@ninadarbaidze correction i made new user and i still can not log in :/ 
![image](https://user-images.githubusercontent.com/75663118/189313451-3e995ea4-5606-4747-9f3d-1c5bd070292d.png)

**Comment by GigaGiorgadze** [comment]
i can only do that with gmail user

**Comment by GigaGiorgadze** [comment]
correction it does not work even in that case
